### ISSUE TITLE
Demoting to standard user if it was already admin

### ISSUE THREAD

**Issue by psaintemarie** [laurentpertois/Temp-Admin#1]
Hi !

First, I have not tried this yet but I use something similar (but more dirty script) at work.

My only feedback would be, as this should be scoped to users that are supposed to be standard and not admin, if, when we run the script, the user is (already) admin, shouldn't we give them $TEMPMINUTES of admin permissions but at the end demote them back to standard ?

(Asking for a friend)

**Comment by laurentpertois** [comment]
Hi,

As of now, the only thing we do for admin is abort :)

But that could be an idea, not sure if we want to demote the existing admins everytime...

**Comment by psaintemarie** [comment]
We just want to do that for the current logged in user. If the scope in Jamf Pro is correct (based on building or team for example), the user should not be an admin on his device. Then if for some reason, he is admin, we give him the $TEMPSECONDS of admin time and then demote. Not sure I'm clear :)

**Comment by laurentpertois** [comment]
I think I get it... definitely could be a switch option to change the script based on a parameter passed...

Need to think about it :)
