### ISSUE TITLE
Invalid in using it with JAMF Self Service!

### ISSUE THREAD

**Issue by unlimitedblade8** [laurentpertois/Temp-Admin#4]
When I use this script in client , I found a problem , Admin already but nothing change in revoking the Current User Admin privileges. I had tried many times , you know , but it didn't work well ! I had change the time to 1 minutes and the result is  as useless as before.

**Comment by unlimitedblade8** [comment]
MacOSX 10.14.0

**Comment by laurentpertois** [comment]
Hi @unlimitedblade8

Sorry I missed your issue when you opened it.

I think it's because of PPPC and since then I added a Configuration Profile to make sure the script to demote the users will execute.

Once again, sorry for the delay
