### ISSUE TITLE
Use of python2 to obtain current user

### ISSUE THREAD

**Issue by grahampugh** [laurentpertois/Temp-Admin#5]
Hi Laurent! Your own `Search-Scripts-In-Jamf` script would flag this script for using python2 to obtain the current user :)  

A simple switch to the common `scutil` method will sort that.

**Comment by laurentpertois** [comment]
Hi Graham,

Fair point! I'll make the change quickly! Thanks for pointing it 😊

**Comment by laurentpertois** [comment]
And voilà, fixed!
